# docker image name
image_name : "gerkone/torcs"

# run module and path. change to your test script location and function
mod_name : "main"
run_path : "driver/run_torcs.py"

# run module and path. change here to your agent algorithm
algo_name: "DDPG"
algo_path: "driver/agents/ddpg/ddpg.py"

# agent hyperparameters
hyperparams:
  actor_lr : 0.00005
  critic_lr : 0.0003
  batch_size : 32
  gamma : 0.99
  guided_steps : 0
  buf_size : 25000
  tau : 0.001
  fcl1_size : 200
  fcl2_size : 600
  actor_update_delay : 2

# dict with key: observation name, val: normalization scale (sensor max value)
sensors:
  track : 200.0
  angle: 3.1415
  speedX : 300.0
  speedY : 300.0
  speedZ : 300.0
  wheelSpinVel : 1.0
  trackPos: 1.0

# environment and training related settings
training:
    # choosen track
    # can be choosen betwen

    # DIRT : dirt-1 dirt-2 dirt-3 dirt-4 dirt-5 dirt-6 mixed-1 mixed-2
    #
    # ROAD : alpine-1 corkscrew e-track-3 g-track-2 ole-road-1 street-1 alpine-2 e-track-6 g-track-3
    #        ruudskogen wheel-1 brondehach e-track-2 forza spring wheel-2 aalborg e-track-1 e-track-5 e-track-1
    #        e-track-5 a-speedway eroad e-track-4 g-track-1
    #
    # OVAL : b-speedway e-speedway g-speedway michigan c-speedway d-speedway f-speedway
    track: "g-track-1"
  # manual throttle control
  throttle : True
  target_speed : 50
  # manual not yet properly supported - leave it False
  gear_change : False
  # set number of steps before restarting the episode
  # max 50 steps per second
  max_steps : 1500
  # total number of episodes
  episodes : 10000
  # number of passes on data
  epochs : 10
  # number of steps before each training
  train_req : 1500
