# docker image name
image_name : "gerkone/torcs"

# run module and path. change to your test script location and function
mod_name : "main"
run_path : "driver/run_torcs.py"

# run module and path. change here to your agent algorithm
algo_name: "DDPG"
algo_path: "driver/agents/ddpg/ddpg.py"

# agent hyperparameters
hyperparams:
  actor_lr : 0.00005
  critic_lr : 0.0003
  batch_size : 32
  gamma : 0.99
  guided_steps : 0
  buf_size : 25000
  tau : 0.001
  fcl1_size : 200
  fcl2_size : 600
  actor_update_delay : 2

# dict with key: observation name, val: normalization scale (sensor max value)
sensors:
  track : 200.0
  angle: 3.1415
  speedX : 300.0
  speedY : 300.0
  speedZ : 300.0
  wheelSpinVel : 1.0
  trackPos: 1.0

# environment and training related settings
training:
  # manual throttle control
  throttle : True
  target_speed : 50
  # manual not yet properly supported - leave it False
  gear_change : False
  # set number of steps before restarting the episode
  # max 50 steps per second
  max_steps : 1500
  # total number of episodes
  episodes : 10000
  # number of passes on data
  epochs : 10
  # number of steps before each training
  train_req : 1500
