# docker image name
image_name : "gerkone/torcs"

# run module and path. change to your test script location and function
mod_name : "main"
run_path : "driver/run_torcs.py"

# # run module and path. change here to your agent algorithm
algo_name: "Simple"
algo_path: "driver/agents/simple_agent_dataset/snakeoil3.py"


# agent hyperparameters
hyperparams:
  target_speed : 120
  max_speed : 300
  noise_scale : 0.7
  save_each : 4
  sway : False
  prefix : ""

# dict with key: observation name, val: normalization scale (sensor max value)
sensors:
  # output
  angle: 3.1415 # at sensors[0]
  track : 200.0 # at sensors[2:-2]
  trackPos: 1.0 # at sensors[:-1]
  # input
  img : 1.0
  # other
  speedX : 1.0


# DO NOT CHANGE THIS
# unless you know what you are doing
driver :
  module : "scr_server"
  index : "0"
  sid : "SCR"
  ports :
    - 3001

# environment and training related settings
training:
  # choosen track
  # can be choosen betwen

  # DIRT : dirt-1
  #
  # ROAD : alpine-1 corkscrew aalborg e-track-1 eroad g-track-1 ruudskogen street-1
  #
  # OVAL : michigan
  track:
    - "g-track-1"
    # - "g-track-1"
    # - "g-track-1"
    # - "street-1"
    # - "a-speedway"
    # - "michigan"
    # - "e-track-2"
    # - "ruudskogen"

  # choosen car
  # can be choosen between
  # RALLY: pw-imprezawrc pw-306wrc
  # GT: car1-trb1
  # OPEN WHEEL: car1-ow1
  car: "car1-trb1"

  # manual throttle control
  throttle : True
  target_speed : 70
  # manual not yet properly supported - leave it False
  gear_change : False
  # set number of steps before restarting the episode
  # max 50 steps per second
  max_steps : 30000
  # total number of episodes
  episodes : 20
  # number of passes on data
  epochs : 10
  # number of steps before each training
  train_req : 1

# resized image dimensions
img_width : 640
img_height : 480
# frame stack size. set to 1 to disable frame stacking
stack_depth: 1
