# docker image name
image_name : "gerkone/torcs"

# run module and path. change to your test script location and function
mod_name : "main"
run_path : "driver/run_torcs_tf2rl.py"

# run module and path. change here to your agent algorithm
algo_name: "PPO_wrapper"
algo_path: "driver/agents/ppo/ppo_wrapper.py"

# agent hyperparameters
hyperparams:
  epochs : 20
  lam : 0.997
  c_1 : 0.8
  c_2 : 0.0001
  horizon : 4000
  clip_ratio : 0.2

  actor_lr : 0.00005
  critic_lr : 0.0005
  batch_size : 50
  fcl1_size : 512
  fcl2_size : 128
  gamma : 0.99

  tau : 0.005
  buf_size : 100000
  n_warmup : 1000
  update_interval : 2
  noise_phi : 0.5

  test_interval : 10000

  # dataset_dir : "dataset/"
  model_dir : "results/PPO"
  # model_dir : "results/DDPG"

# dict with key: observation name, val: normalization scale (sensor max value)
sensors:
  speedX : 1.0
  speedZ : 1.0
  speedY : 1.0
  wheelSpinVel : 1.0
  track : 200.0
  angle: 3.1415
  trackPos: 1.0


# DO NOT CHANGE THIS
# unless you know what you are doing
driver :
  module : "scr_server"
  index : "0"
  sid : "SCR"
  ports :
    - 3001

# environment and training related settings
training:
    # choosen track
    # can be choosen betwen

    # DIRT : dirt-1
    #
    # ROAD : alpine-1 corkscrew aalborg e-track-1 eroad g-track-1 ruudskogen street-1
    #
    # OVAL : michigan
  track:
    - "aalborg"
    - "street-1"
    - "michigan"
    - "g-track-1"

  # choosen car
  # can be choosen between
  # RALLY: pw-imprezawrc pw-306wrc
  # GT: car1-trb1
  # OPEN WHEEL: car1-ow1
  car: "car1-trb1"

  # manual throttle control
  throttle : True
  target_speed : 50
  # manual not yet properly supported - leave it False
  gear_change : False
  # set number of steps before restarting the episode
  # max 50 steps per second
  max_steps : 100000
  # number of passes on data
  epochs : 12
  # number of steps before each training
  train_req : 1000
  # rl algorithm - change this to choose between DDPG and PPO
  algo : "PPO"
