# docker image name
image_name : "gerkone/torcs"

# run module and path. change to your test script location and function
mod_name : "main"
run_path : "driver/run_torcs_tf2rl.py"

# run module and path. change here to your agent algorithm
algo_name: "PPO_wrapper"
algo_path: "driver/agents/ppo/ppo_wrapper.py"

# agent hyperparameters
hyperparams:
  actor_lr : 0.00005
  critic_lr : 0.0005
  batch_size : 32
  gamma : 0.99
  buf_size : 100000
  epochs : 10
  horizon : 2048

  lam : 0.95
  tau : 0.005
  gamma : 0.99

  c_1 : 0.5
  c_2 : 0.001


  fcl1_size : 200
  fcl2_size : 300
  actor_update_delay : 2

  save_dir : "driver/agents/ppo/model"

# dict with key: observation name, val: normalization scale (sensor max value)
sensors:
  speedZ : 1.0
  speedY : 1.0
  wheelSpinVel : 1.0
  track : 200.0
  speedX : 1.0
  angle: 3.1415
  trackPos: 1.0


# DO NOT CHANGE THIS
# unless you know what you are doing
driver :
  module : "scr_server"
  index : "0"
  sid : "SCR"
  port : 3001
# environment and training related settings
training:
  # choosen track
  # can be choosen betwen

  # DIRT : dirt-1 dirt-2 dirt-3 dirt-4 dirt-5 dirt-6 mixed-1 mixed-2
  #
  # ROAD : alpine-1 corkscrew e-track-3 g-track-2 ole-road-1 street-1 alpine-2 e-track-6 g-track-3
  #        ruudskogen wheel-1 brondehach e-track-2 forza spring wheel-2 aalborg e-track-1 e-track-5 e-track-1
  #        e-track-5 eroad e-track-4 g-track-1
  #
  # OVAL : a-speedway b-speedway e-speedway g-speedway michigan c-speedway d-speedway f-speedway
  track:
    - "street-1"

  # choosen car
  # can be choosen between
  # 155-DTM       car1-trb3  p406        kc-conrero        kc-grifo   pw-corollawrc
  # acura-nsx-sz  car2-trb1  kc-2000gt   kc-corvette-ttop  kc-gt40    pw-evoviwrc
  # baja-bug      car3-trb1  kc-5300gt   kc-daytona        kc-gto     pw-focuswrc
  # buggy         car4-trb1  kc-a110     kc-db4z           kc-p4      pw-imprezawrc
  # car1-ow1      car5-trb1  kc-alfatz2  kc-dbs            pw-306wrc
  # car1-stock1   car6-trb1  kc-bigh     kc-dino           p406
  # car1-stock2   car7-trb1  kc-cobra    kc-ghibli         pw-206wrc
  # car1-trb1     car8-trb1  kc-coda     kc-giulietta
  car: "car1-trb1"

  # manual throttle control
  throttle : True
  target_speed : 50
  # manual not yet properly supported - leave it False
  gear_change : False
  # set number of steps before restarting the episode
  # max 50 steps per second
  max_steps : 2000
  # total number of episodes
  episodes : 3000
  # number of passes on data
  epochs : 12
  # number of steps before each training
  train_req : 1000
