# docker image name
image_name : "gerkone/torcs"

# run module and path. change to your test script location and function
mod_name : "main"
run_path : "driver/run_torcs.py"

# run module and path. change here to your agent algorithm
algo_name: "DDPG"
algo_path: "driver/agents/ddpg/ddpg.py"

# agent hyperparameters
hyperparams:
  actor_lr : 0.00005
  critic_lr : 0.0005
  batch_size : 64
  gamma : 0.99
  guided_episode : 2
  buf_size : 500000
  tau : 0.001
  fcl1_size : 200
  fcl2_size : 300
  noise_phi : 0.5

  save_dir : "driver/agents/ddpg/model"

# dict with key: observation name, val: normalization scale (sensor max value)
sensors:
  speedZ : 1.0
  speedY : 1.0
  wheelSpinVel : 1.0
  track : 200.0
  speedX : 1.0
  angle: 3.1415
  trackPos: 1.0

# DO NOT CHANGE THIS
# unless you know what you are doing
driver :
  module : "scr_server"
  index : "0"
  sid : "SCR"
  ports :
    - 3001
# environment and training related settings
training:
  # choosen track
  # can be choosen betwen

  # DIRT : dirt-1
  #
  # ROAD : alpine-1 corkscrew aalborg e-track-1 eroad g-track-1 ruudskogen street-1
  #
  # OVAL : michigan
  track:
    - "g-track-1"

  # choosen car
  # can be choosen between
  # RALLY: pw-imprezawrc pw-306wrc
  # GT: car1-trb1
  # OPEN WHEEL: car1-ow1
  car: "car1-trb1"

  # manual throttle control
  throttle : True
  target_speed : 50
  # manual not yet properly supported - leave it False
  gear_change : False
  # set number of steps before restarting the episode
  # max 50 steps per second
  max_steps : 1500
  # total number of episodes
  episodes : 3000
  # number of passes on data
  epochs : 4
  # number of steps before each training
  train_req : 1500
