# docker image name
image_name : "gerkone/torcs"

# run module and path. change to your test script location and function
mod_name : "main"
run_path : "driver/run_torcs.py"

# # run module and path. change here to your agent algorithm
algo_name: "Simple"
algo_path: "driver/agents/berniw_agent/collect.py"


# agent hyperparameters
hyperparams:

# dict with key: observation name, val: normalization scale (sensor max value)
sensors:
  distRaced : 1.0
  totalTime : 1.0
  trackLen : 1.0

  speedZ : 1.0
  speedY : 1.0
  wheelSpinVel : 1.0
  track : 200.0
  speedX : 1.0
  angle: 3.1415
  trackPos: 1.0
  damage : 1.0

  steer : 1.0
  throttle : 1.0

# DO NOT CHANGE THIS
# unless you know what you are doing
driver :
  module : "berniw"
  index : "1"
  sid : "TEL"
  ports :
    - 3001

# environment and training related settings
training:
  # choosen track
  # can be choosen betwen

  # DIRT : dirt-1
  #
  # ROAD : alpine-1 corkscrew aalborg e-track-1 eroad g-track-1 ruudskogen street-1
  #
  # OVAL : michigan
    - alpine-1
    - corkscrew
    - aalborg
    - e-track-1
    - eroad
    - g-track-1
    - ruudskogen
    - street-1
    - michigan

  # choosen car
  # can be choosen between
  # RALLY: pw-imprezawrc pw-306wrc
  # GT: car1-trb1
  # OPEN WHEEL: car1-ow1
  car: "car1-trb1"

  # manual throttle control
  throttle : True
  target_speed : 50
  # manual not yet properly supported - leave it False
  gear_change : False
  # set number of steps before restarting the episode
  # max 50 steps per second
  max_steps : -1
  # total number of episodes
  episodes : 1
  # number of passes on data
  epochs : 0
  # number of steps before each training
  train_req : 1

# resized image dimensions
img_width : 160
img_height : 120
# frame stack size. set to 1 to disable frame stacking
stack_depth: 1
