# docker image name
image_name : "test_torcs" #"gerkone/torcs"

# run module and path. change to your test script location and function
mod_name : "main"
run_path : "driver/run_torcs.py"

# # run module and path. change here to your agent algorithm
algo_name: "Simple"
algo_path: "driver/agents/simple_agent_dataset/snakeoil3.py"


# agent hyperparameters
hyperparams:
  target_speed : 90
  max_speed : 300
  noise_scale : 0.3
  frame_freq: 3
  max_steps : 5000
  train_req : 1000

# dict with key: observation name, val: normalization scale (sensor max value)
sensors:
  track : 200.0
  angle: 3.1415
  speedX : 300.0
  speedY : 300.0
  speedZ : 300.0
  # wheelSpinVel : 1.0
  # rpm : 10000
  trackPos: 1.0
  # VISION SENSOR. set to turn vision on
  img: 255.0

# environment and training related settings
training:
  # manual throttle control
  throttle : True
  target_speed : 50
  # manual not yet properly supported - leave it False
  gear_change : False
  # set number of steps before restarting the episode
  # max 50 steps per second
  max_steps : 5000
  # total number of episodes
  episodes : 10
  # number of passes on data
  epochs : 10
  # number of steps before each training
  train_req : 1000

# resized image dimensions
img_width : 128
img_height : 96
# frame stack size. set to 1 to disable frame stacking
stack_depth: 1
