# docker image name
image_name : "gerkone/torcs"

# run module and path. change to your test script location and function
mod_name : "main"
run_path : "driver/run_torcs.py"

# # run module and path. change here to your agent algorithm
# algo_name: "Simple"
# algo_path: "driver/agents/simple_agent/snakeoil3.py"

# run module and path. change here to your agent algorithm
algo_name: "DDPG"
algo_path: "driver/agents/ddpg/ddpg.py"

# agent hyperparameters
hyperparams:
  actor_lr : 0.00001
  critic_lr : 0.00003
  batch_size : 64
  gamma : 0.99
  rand_steps : 0
  buf_size : 100000
  tau : 0.001
  fcl1_size : 256
  fcl2_size : 64
  actor_update_delay : 2
  img_width : 128
  img_height : 96
  stack_depth: 3
  # target_speed : 50
  # max_speed : 300

# dict with key: observation name, val: normalization scale (sensor max value)
sensors:
  track : 200.0
  angle: 3.1415
  speedX : 300.0
  speedY : 300.0
  speedZ : 300.0
  wheelSpinVel : 1.0
  # # rpm : 10000
  trackPos: 1.0
  # VISION SENSOR. set to turn vision on
  # img: 255.0

# environment and training related settings
training:
  # manual throttle control
  throttle : False
  target_speed : 50
  # manual not yet properly supported - leave it False
  gear_change : False
  # set number of steps before restarting the episode
  # approx 50 steps per second
  max_steps : 4000
  # total number of episodes
  episodes : 10000
  # number of passes on data
  epochs : 20
  # number of events before each training
  train_freq : 5

# resized image dimensions
img_width : 128
img_height : 96
# frame stack size. set to 1 to disable frame stacking
stack_depth: 3
